apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        {{- if .Values.configMap.enabled }}
        - name: {{ .Values.configMap.depname }}
          mountPath: {{ .Values.configMap.fileLocation }}
          subPath: {{ .Values.configMap.subPath }}
          readOnly: true
        {{- end }}
        # - mountPath: {{ .Values.deployment.aloglocation }}
        #   name: {{ .Values.deployment.alogname }}
        resources:
            # {{- toYaml .Values.deployment.resources | nindent 12 }}
        command: ["npm"]
        args: ["run", "start"]
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
      volumes:
      {{- if .Values.configMap.enabled }}
      - name: {{ .Values.configMap.depname }}
        configMap:
          name: {{ .Values.configMap.name }}
      {{- end }}
      # - name: {{ .Values.deployment.alogname }}
      #   persistentVolumeClaim:
      #     claimName: {{ .Values.deployment.pvcname }}
