apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: {{ .Values.deployment.name }}
